import Link from 'next/link';
import { brandRamp } from '@palette-canvas/design-tokens';
import { PublicNav, PublicFooter } from '../components/PublicChrome';

export const metadata = { title: 'Get started — Palette Canvas' };

/**
 * Sign-up branching (spec §8.3). Exactly two paths, matching the two roles that
 * can actually request access. Guest is deliberately absent: §8.3 is explicit
 * that Guest never has a sign-up path, because a Guest link is generated by an
 * Account/Production Manager, not claimed. That absence is stated in prose
 * below rather than offered as a third card, so it reads as a boundary rather
 * than as an option that happens to be missing.
 */
const PATHS = [
  {
    id: 'employee',
    audience: 'Employee / Account Manager / Management',
    title: "I'm joining a Palette Canvas team",
    body: 'Provisioned internally: this path collects a request, not an instant account. Your access is created by administration and follows the role you are given.',
    action: 'Contact your workspace administrator',
    href: '/help',
    tone: brandRamp.accent,
  },
  {
    id: 'agency',
    audience: 'Client',
    title: "I'm a Partner Agency",
    body: 'A self-serve request tied to an active or pending engagement. It is verified against a real engagement before activation — not an open sign-up anyone can complete.',
    action: 'Start an application',
    href: '/help',
    tone: brandRamp.violet,
  },
];

export default function SignupPage() {
  return (
    <>
      <PublicNav />
      <main style={{ maxWidth: 1120, margin: '0 auto', padding: 'clamp(40px, 6vw, 72px) clamp(16px, 4vw, 48px)' }}>
        <span style={{ color: 'var(--ink-faint)', fontSize: 12, textTransform: 'uppercase', letterSpacing: '0.12em' }}>Get started</span>
        <h1 style={{ fontFamily: 'var(--display)', fontSize: 'clamp(30px, 4.5vw, 44px)', margin: '10px 0 12px' }}>
          Which best describes you?
        </h1>
        <p style={{ color: 'var(--ink-dim)', fontSize: 15, lineHeight: 1.7, maxWidth: 640, margin: 0 }}>
          Access to a workspace is issued, not claimed. Two roles can request it here; everyone else arrives by invitation.
        </p>

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(260px, 1fr))', gap: 16, marginTop: 36 }}>
          {PATHS.map((p) => (
            <article key={p.id} style={{ ...panelCard, borderColor: 'var(--line)' }}>
              <span style={{ color: p.tone, fontSize: 11, textTransform: 'uppercase', letterSpacing: '0.1em' }}>{p.audience}</span>
              <h2 style={{ fontFamily: 'var(--display)', fontSize: 20, margin: '10px 0 8px' }}>{p.title}</h2>
              <p style={{ color: 'var(--ink-dim)', fontSize: 14, lineHeight: 1.6, margin: 0, flex: 1 }}>{p.body}</p>
              <Link href={p.href} style={{ color: p.tone, fontSize: 13, textDecoration: 'none', marginTop: 14 }}>
                {p.action} →
              </Link>
            </article>
          ))}
        </div>

        <div style={{ ...panelCard, marginTop: 16, borderColor: 'var(--line-strong)' }}>
          <span style={{ color: brandRamp.magenta, fontSize: 11, textTransform: 'uppercase', letterSpacing: '0.1em' }}>Guest</span>
          <h2 style={{ fontFamily: 'var(--display)', fontSize: 20, margin: '10px 0 8px' }}>Client or third party? You will be invited.</h2>
          <p style={{ color: 'var(--ink-dim)', fontSize: 14, lineHeight: 1.6, margin: 0 }}>
            Guest is the platform&apos;s narrowest, most deliberately controlled access tier, so it has no sign-up path at all — by
            design, not by omission. An Account or Production Manager generates your link, scoped to the specific work you need to
            see, and it expires on its own. If you are expecting one, your account contact can confirm its status.
          </p>
        </div>

        <p style={{ color: 'var(--ink-faint)', fontSize: 13, marginTop: 32, maxWidth: 640, lineHeight: 1.6 }}>
          By requesting access you confirm you have read the{' '}
          <Link href="/legal/terms" style={{ color: 'var(--ink-dim)' }}>terms of service</Link> and the{' '}
          <Link href="/legal/privacy" style={{ color: 'var(--ink-dim)' }}>privacy notice</Link>.
        </p>
      </main>
      <PublicFooter />
    </>
  );
}

const panelCard: React.CSSProperties = {
  display: 'flex',
  flexDirection: 'column',
  padding: 22,
  borderRadius: 16,
  border: '1px solid var(--line)',
  background: 'var(--brand-raise)',
};